version: '3.8'

services:
  mysql-backup-system:
    build: .
    network_mode: "host"
    volumes:
      - ./backups:/app/backups
      - ./logs:/app/logs
      - ./ssh:/root/.ssh:ro
      - ./mysql-backup-system:/app/mysql-backup-system:ro  # Adiciona essa linha
    restart: unless-stopped
