version: '3.8'

services:
  mysql-backup-system:
    build: .
    network_mode: "host"  # usa rede do host diretamente
    volumes:
      - ./backups:/app/backups
      - ./logs:/app/logs
      - ./config:/root/.mysql-backup-config
      - ./ssh:/root/.ssh:ro 
    restart: unless-stopped
