version: '3.8'

services:
  mysql-backup-system:
    build: .
    ports:
      - "8030:8030"
    volumes:
      - ./backups:/app/backups
      - ./logs:/app/logs
      - config_data:/root   # volume dedicado ao .config
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3356
      - MYSQL_USER=admroot
      - MYSQL_PASSWORD=c2efe3d6438743b585c996f63c76ae3c
      - MYSQL_DATABASE=backsystem
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=backsystem
      - MYSQL_USER=admroot
      - MYSQL_PASSWORD=c2efe3d6438743b585c996f63c76ae3c
    ports:
      - "3356:3356"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
  config_data:  # novo volume para armazenar o .config
